sudo: required
services:
  - docker
before_install:
  - docker build -t thakursachin467/event-manager-client -f Dockerfile.dev .
script:
  - docker run thakursachin467/event-manager-client npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Event-manager-"
  env: "EventManager-env"
  bucket_name: "elasticbeanstalk-us-east-2-456128121975"
  bucket_path: "Event-manager-"
  on:
    branch: master
  access_key_id: "$Access_key_ID"
  secret_access_key:
    secure: "$Secret_access_key"



